### ISSUE TITLE
Avatar not displayed on other pages, except Account

### ISSUE THREAD

**Issue by najbo** [rainlab/vanilla-theme#9]
Hi,

I noticed that the avatar displayed in the navbar does nos show correctly, except on the Account page. That's because the "avatar" relation on the other frontend pages is not loaded.

There's a condition in file "HasModelAttributes"  in the User Model Plugin: 

```
public function getAvatarUrlAttribute()
{
    return $this->relationLoaded('avatar')
        ? $this->getAvatarThumb()
        : null;
}
```

Would it be reasonable to remove the $this>relationLoaded condition here, and just return the getAvatarThumb() ?
Or add `$this->loadMissing('avatar');` before  ? ... but this certainly would make nonsense.

Thanks for your help.
Jan

**Comment by daftspunk** [comment]
Hey Jan!

This is needed since the `avatar_url` is appended to the JSON serialization of the model.

```php
/**
 * appends accessors to the model's array form.
 */
protected $appends = [
    'avatar_url'
];
```

It means if the avatar relation isn't loaded, it triggers an N+1 performance issue when returning a collection of users (1 query per user). It might make more sense to replace it with a `getAvatarThumb` in the theme, which will force it to load.

**Comment by najbo** [comment]
Hi Daft !

Thanks for the suggestion ; I made this small PR #10 

See ya :-)
